some optimization for ce db
PaddlePaddle/MacroCE pull request #57
Opened 2018-05-28 08:25 UTC by guochaorong

1. 增加db相应的接口函数
2. 目前db使用一张表， 对表的查询比较简单。 以后扩展性可能好一些，目前没有太多的效果，
请春伟帮忙看看是不是你期望的？

2018-05-29 11:59 UTC, Superjomn requested changes
用户程序应该只需要跟 `KpiRecord`, `TaskRecord` 打交道，隐藏 detail.

2018-05-29 11:59 UTC, Superjomn commented on web/api.py
> +    '''the table contails all of the records'''
comment 格式有问题，一组 ''' 就可以了

2018-05-29 11:59 UTC, Superjomn commented on web/api.py
> +        return  db.finds(self.table, {'type': 'kpi'})
多了空格

2018-05-29 11:59 UTC, Superjomn commented on web/api.py
> +class DetailRecord:
感觉这个类没啥用，有 `KpiRecord`, `TaskRecord` 两个就可以存储所有的信息了吧

或者 DetailRecord 变成 `KpiRecord` 的一个工具类，理论上用户有上面两个数据格式就可以了，不需要知道数据库表的格式

2018-05-29 11:59 UTC, Superjomn commented on web/api.py
> +def query_commit_from_details(commit):
下面的函数的返回值都应该是 `KpiRecord` 和 `TaskRecord` 这两种标准数据类型，而不是其他定制类型，否则无法起到简化和清晰化数据类型的目的

2018-05-29 11:59 UTC, Superjomn commented on web/main.py
> +    commits = query_all_commits_from_details()
除了 kpi.py ，其他使用的程序不需要跟 `DetailRecord` 打交道，不然还是跟之前的使用方式一样，非常不清晰。

2018-05-29 12:07 UTC, guochaorong commented on web/main.py
> +    commits = query_all_commits_from_details()
没看明白 kpi.py 本来也不需要跟DetailRecord 交互？  现在存数据是 persistence.py

2018-06-14 06:30 UTC, guochaorong commented
https://github.com/PaddlePaddle/continuous_evaluation/pull/59 这个pr进了该功能

2018-06-14 06:30 UTC, closed without merging