Adjust db struct to make faster and clearer
PaddlePaddle/MacroCE pull request #59
Opened 2018-05-30 16:43 UTC by guochaorong

2018-06-01 04:31 UTC, Superjomn commented on web/api.py
> +                commit_ids.append(commit['commitid'])
注释里是
> returns: list of CommitRecord

返回值应该是  [CommitRecord]

2018-06-01 04:32 UTC, Superjomn commented on web/api.py
> +    def query_a_commit_info(self):
get_commit_record(self)

2018-06-01 04:43 UTC, Superjomn requested changes
感觉差的比较多，之前好像一起定过接口，具体字段没有问题，但不需要暴露这么多接口。

下面的几个 method 就可以了。

```python
class CommitRecord:
    @staticmethod
    def get_all(): 
        ''' Return list of CommitRecord '''
        pass

    def get_all_records(self):
         ''' Return list of TaskRecord '''
         pass

class TaskRecord:
    pass

class KpiRecord:
    pass
```

用户使用案例

1. 获取所有的 commitid
```python
commits = CommitRecord.get_all()
commitids = [c.commitid for c in commits]
```
2. 获取一个 commitid 下所有的 task 记录
```
# some commit
commit = commits[k]
task_records = commit.get_all_records()
```

3. 遍历一个 commit 下所有的 kpi record
```python
for task_record in commit.get_all_records():
    for kpi_record in task_record.kpis:
        print(kpi_record.values)
```

2018-06-01 04:43 UTC, Superjomn commented on web/api.py
> +    def query_all_commit_infos():
这个函数不需要，用户可以直观用
```python
commit_records = CommitRecord.get_all()
# if want to get all commit id
commit_ids = [c.commit_id for c in commit_records]
```

2018-06-01 04:43 UTC, Superjomn commented on web/api.py
> +    def get_tasks_from_details(commit):
不需要暴露 details

2018-06-12 08:46 UTC, Superjomn commented on web/api.py
>      def get_kpi_details(self):
这个函数是不是private 就可以了，用户需要显式调用吗

2018-06-12 09:11 UTC, guochaorong commented on web/api.py
>      def get_kpi_details(self):
脚本外目前没有调用的。就是拿1个task 的 kpi infos。 
        returns dict of KpiRecord
                    keys equal to kpi name,
                    values equal to KpiRecord'''

现在在commitRecord 类里面调用了这个函数，  改个名字 get_kpis？ 是不是可以暴露出去

2018-06-12 09:14 UTC, Superjomn commented on web/api.py
>      def get_kpi_details(self):
一个 TaskRecord 应该直接包含多个 KpiRecord，这个接口应该不需要额外调，所以不一定需要

2018-06-12 09:24 UTC, guochaorong commented on web/api.py
>      def get_kpi_details(self):
嗯啊    这是个现有鸡还是先有蛋的问题， 如果他仅仅初始化了一个TaskRecord 对象，  还没调用任何方法，  这个对象还是空的。

现在在CommitRecord 这个类里面用到了TaskRecord 里面的这个方法，  如果写成私有的CommitRecord类还能调用到它么

2018-06-12 09:51 UTC, guochaorong commented on web/api.py
>      def get_kpi_details(self):
感觉改个更general的名字， 比如get_kpis， 然后作为public 方法看着还行？

2018-06-13 00:57 UTC, Superjomn approved these changes
LGTM

2018-06-13 03:18 UTC, merged